version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    environment:
      RAILS_ENV: test
      Z_LOCALES: "en-us:de-de"
      REDIS_URL: redis://redis:6379
      CI_SKIP_ASSETS_PRECOMPILE: 'true'
      CI_SKIP_DB_RESET: 'true'      
    resource_class: medium
    steps:
      - checkout
      - run: echo "starting"
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - run: sudo apt-get update
      - run: sudo apt install postgresql-10
      - run: echo 'postgres' | psql -U postgres -h localhost -c "CREATE USER zammad WITH PASSWORD 'zammad';"
      - run: sudo apt install redis-server
      - run: sudo apt-get install -y -f optipng jhead imagemagick libimlib2 openssl direnv shellcheck libimlib2-dev gettext xvfb libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev
      - run: echo '127.0.0.1 redis postgresql' | sudo tee -a /etc/hosts
      - run: bundle install --path vendor/bundle
      - run: yarn install
      - run: yarn cypress:install
      - run: bundle exec ruby .gitlab/configure_environment.rb
      - run: bundle exec rake zammad:db:init
      - run: for FILE in i18n/*.pot i18n/*.po; do echo "Checking $FILE"; msgfmt -o /dev/null -c "$FILE"; done
      - run: bundle exec rails generate zammad:translation_catalog --check
      - run: bundle exec brakeman -o /dev/stdout -o tmp/brakeman-report.html
      - run: bundle exec rails zeitwerk:check
      - run: .gitlab/check_graphql_api_consistency.sh
      - run: bundle exec .rubocop/validate_todos.rb
      - run: bundle exec rubocop --parallel
      - run: yarn lint:css
      - run: yarn lint
      - run: bundle exec rake assets:precompile
      - run: yarn test || true
      - run: yarn test:ci:ct
      - run: bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb" -t ~searchindex -t ~integration -t ~required_envs
      - run: bundle exec rake zammad:db:reset
      - run: bundle exec rake test:units      
