version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.3
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: zammad
          POSTGRES_PASSWORD: zammad
      - image: circleci/redis:6.2
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y -f optipng jhead imagemagick libimlib2 openssl direnv shellcheck libimlib2-dev
      - run: echo '127.0.0.1 redis postgresql' | sudo tee -a /etc/hosts
      - run: bundle install --path vendor/bundle
      - run: yarn install
      - run: yarn cypress:install
      - run: bundle exec ruby .gitlab/configure_environment.rb
      - run: bundle exec rake zammad:db:init
      - run: for FILE in i18n/*.pot i18n/*.po; do echo "Checking $FILE"; msgfmt -o /dev/null -c "$FILE"; done
      - run: bundle exec rails generate zammad:translation_catalog --check
      - run: bundle exec brakeman -o /dev/stdout -o tmp/brakeman-report.html
      - run: bundle exec rails zeitwerk:check
      - run: .gitlab/check_graphql_api_consistency.sh
      - run: bundle exec .rubocop/validate_todos.rb
      - run: bundle exec rubocop --parallel
      - run: yarn lint:css
      - run: yarn lint
      - run: bundle exec rake assets:precompile
      - run: yarn test
      - run: yarn test:ci:ct
      - run: bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb" -t ~searchindex -t ~integration -t ~required_envs
      - run: bundle exec rake zammad:db:reset
      - run: bundle exec rake test:units
      - run: ruby -I test/ test/integration/object_manager_test.rb
      
